[[interaction]]
name = "buy_kite"
valence = 80
arousal = 70
dominance = 50

[[interaction]]
name = "sell_kite"
valence = -70
arousal = -60
dominance = -40

[[interaction]]
name = "ignore"
valence = -60
arousal = -50
dominance = -40
